Fix RPM spec require parsing issue
 ---> rpmbuild -ba --define '_sourcedir /root/BUILD/rpm_spec' --define '_srcrpmdir /root/BUILD/rpms/x86_64' --define '_rpmdir /root/BUILD/rpms' manageiq.spec
error: line 307: Dependency tokens must begin with alpha-numeric, '_' or '/': Requires: core-utils     # rpm %pre calls uses id