Fix pylxca build failure due to missing source file
Error:
ERROR: Exception(./python-pylxca.spec) Config(centos-stream-10-x86_64) 0 minutes 48 seconds
INFO: Results and/or logs in: /var/lib/mock/centos-stream-10-x86_64/result
ERROR: Command failed:
 # bash --login -c '/usr/bin/rpmbuild -bs --noclean --target x86_64 --nodeps /builddir/build/SPECS/python-pylxca.spec'

Error: Process completed with exit code 1.