Run license finder before scrubbing to avoid issues with missing .yarn
Error:
LicenseFinder::NPM: is active
LicenseFinder::Yarn: is active
.../gems/license_finder-7.0.1/lib/license_finder/package_managers/yarn.rb:90:in `block in yarn_version': Command 'yarn -v' failed to execute: node:internal/modules/cjs/loader:1210 (RuntimeError)
  throw err;
  ^

Error: Cannot find module '...../.yarn/releases/yarn-4.12.0.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)
    at Module._load (node:internal/modules/cjs/loader:1038:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

CP4AIOPS-23665